# Generated by Django 2.2.5 on 2021-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equip_id', models.BigIntegerField(blank=True, null=True)),
                ('run_start_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('measurement_date', models.DateTimeField(blank=True, null=True)),
                ('block_no', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('evaluation_place', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('category', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('off_point', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sub_category', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ana_summary',
                'managed': False,
            },
        ),
    ]
